### ISSUE TITLE
Missing Button for reset last score

### ISSUE THREAD

**Issue by famnoah** [screendriver/seniorenzocken#15]
Add a new Button to reset last score. Mayme back to start score 0 : 0.
Only reset score without sound.

**Comment by screendriver** [comment]
Is this all about to edit the last entered score? For example you clicked _"next round"_ and made a mistake when entering the score?

**Comment by famnoah** [comment]
yes, maybe all scores are stored in an array. So it would be easy to go back.

**Comment by screendriver** [comment]
Resolved in 9e75fe2ab129ec2c29ce02e6b784012b0fa28b87 🙂
