### ISSUE TITLE
Add interim after each game by using added sounds

### ISSUE THREAD

**Issue by famnoah** [screendriver/seniorenzocken#8]
[sound.zip](https://github.com/screendriver/seniorenzocken/files/9945870/sound.zip)

**Comment by famnoah** [comment]
sound 0
[sound_null.zip](https://github.com/screendriver/seniorenzocken/files/10050351/sound_null.zip)

**Comment by famnoah** [comment]
sound rest
[sound_rest.zip](https://github.com/screendriver/seniorenzocken/files/10050778/sound_rest.zip)

**Comment by screendriver** [comment]
Closed because implemented 🥳
